name: "Start minikube"
description: "Run a minikube cluster with a local registry"
author: "fgiorgetti@gmail.com"
runs:
  using: "composite"
  steps:
    - id: start-local-registry
      shell: bash
      run: |
        docker run -d -p 5000:5000 --restart always --name registry registry
    - id: install-kubectl
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    - id: install-conntrack
      shell: bash
      run: sudo apt-get install -y conntrack
    - id: install-minikube
      shell: bash
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
    - id: prepare-environment
      shell: bash
      run: |
        IPADDR="$(ifconfig eth0 | grep "inet " | awk '{print $2}')"
        QPID_DISPATCH_IMAGE="${IPADDR}:5000/qdrouterd:latest"
        echo "IPADDR=${IPADDR}"
        echo "QPID_DISPATCH_IMAGE=${QPID_DISPATCH_IMAGE}"
        echo "IPADDR=${IPADDR}" >> ${GITHUB_ENV}
        echo "QPID_DISPATCH_IMAGE=${QPID_DISPATCH_IMAGE}" >> ${GITHUB_ENV}
    - id: run-minikube
      shell: bash
      run: |
        mkdir $HOME/.kube && touch $HOME/.kube/config && chmod 600 $HOME/.kube/config
        export CHANGE_MINIKUBE_NONE_USER=true
        minikube start --driver=docker --insecure-registry ${IPADDR}:5000
