FROM fedora:30

RUN dnf install -y gcc gcc-c++ make cmake cyrus-sasl-devel libuuid-devel libwebsockets-devel nodejs openssl-devel python3-devel swig wget patch findutils libnghttp2-devel && dnf clean all -y
