#!/usr/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then
    make
else
    make ROUTER_SOURCE_URL=http://github.com/apache/qpid-dispatch/archive/master.tar.gz PROTON_SOURCE_URL=http://github.com/apache/qpid-proton/archive/master.tar.gz
fi

if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
    # build, run tests and if all worked publish a nightly image
    make buildimage pushlocal test push DOCKER_TAG=nightly || exit 1
elif [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    # build, run tests and if all worked publish DOCKER_TAG (default) image tag
    make buildimage pushlocal test push || exit 1
    # if test passed earlier, simply tag and push latest
    make push DOCKER_TAG=latest
else
    # simply build and run tests
    make buildimage pushlocal test || exit 1
fi
