name: Manually build and publish qdrouterd image
on:
  workflow_dispatch:
    inputs:
      routerSourceUrl:
        description: 'Qpid Dispatch Router source code url that returns a tar ball for a given branch'
        required: true
        default: 'http://github.com/apache/qpid-dispatch/archive/main.tar.gz'
      protonSourceUrl:
        description: 'Qpid Proton source code url that returns a tar ball for a given branch'
        required: true
        default: 'http://github.com/apache/qpid-proton/archive/main.tar.gz'
      dockerTag:
        description: 'Docker tag to use for the qdrouterd image'
        required: true
        default: 'custom'
jobs:
  build-nightly:
    name: Build and publish qdrouterd image
    runs-on: ubuntu-latest
    steps:
      - run: |
          # validate DOCKER_TAG
          [[ ! "${DOCKER_TAG}" =~ ^[a-z0-9][a-z0-9.-]+[a-z0-9]$ ]] && echo "invalid tag - it must begin and end with letter or digit and contains - and ." && exit 1
          protected=(latest nightly master)
          for ptag in ${protected[@]}; do
            if [[ "${ptag}" = "${DOCKER_TAG}" ]]; then
              echo "${ptag} cannot be used (protected tag)"
              exit 1
            fi
          done
        env:
          DOCKER_TAG: '${{github.event.inputs.dockerTag}}'
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: ./.github/actions/minikube
      - run: |
          # build, run tests and if all worked publish a custom image
          make ROUTER_SOURCE_URL=${ROUTER_SOURCE_URL} PROTON_SOURCE_URL=${PROTON_SOURCE_URL}
          make buildimage pushlocal test push DOCKER_TAG=${{DOCKER_TAG}} || exit 1
        env:
          DOCKER_USER: '${{ secrets.DOCKER_USER }}'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
          ROUTER_SOURCE_URL: '${{github.event.inputs.routerSourceUrl}}'
          PROTON_SOURCE_URL: '${{github.event.inputs.protonSourceUrl}}'
          DOCKER_TAG: '${{github.event.inputs.dockerTag}}'
