name: Build and test latest dispatch and proton
on: pull_request
jobs:
  build:
    name: Build and test latest dispatch and proton
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: ./.github/actions/minikube
      - run: |
          make
          # simply build and run tests
          make buildimage pushlocal test || exit 1
