name: Build and Publish qdrouterd image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Publish qdrouterd image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: ./.github/actions/minikube
      - run: |
          make
          # build, run tests and if all worked publish DOCKER_TAG (default) image tag
          make buildimage pushlocal test push || exit 1
          # if test passed earlier, simply tag and push latest
          make push DOCKER_TAG=latest
        env:
          DOCKER_USER: '${{ secrets.DOCKER_USER }}'
          DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
